### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by CarePackage360** [AlphaKnights/alphaknights.github.io#6]
Jekyll isn't letting me do favicon. I've tried:
`<link rel="shortcut icon" type="image/png" href="{{site.url}}/favicon-96x96.png">`
`<link rel="shortcut icon" type="image/png" href="/favicon-96x96.png">`
`<link rel="shortcut icon" type="image/png" href="{{ "/favicon-96x96.png" | prepend: site.baseurl }}" >`

**Comment by tjhorner** [comment]
`type="image/png"` is invalid for favicons. Browsers will automatically load a `favicon.ico` from the root of the site (because of some dumb choice made in the 90s), so just put it there.

**Comment by CarePackage360** [comment]
I did what you said and it worked for Firefox, IE, and Google Chrome as far as I know. Microsoft Edge does not take .ico format, but instead it takes .png. How do I add it to the Microsoft Edge browser?

**Comment by tjhorner** [comment]
nobody cares about edge
